--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mei/Pictures/wallpaper/104580093_p0.jpg"

-- Special
background="#0b0a0a"
foreground="#d4d9d3"
cursor="#d4d9d3"

-- Colors
color0="#0b0a0a"
color1="#5A6A8E"
color2="#807F80"
color3="#6E8D9A"
color4="#8E8E8E"
color5="#9FA09F"
color6="#AFAFAF"
color7="#d4d9d3"
color8="#949793"
color9="#5A6A8E"
color10="#807F80"
color11="#6E8D9A"
color12="#8E8E8E"
color13="#9FA09F"
color14="#AFAFAF"
color15="#d4d9d3"
