# Shell variables
# Generated by 'wal'
wallpaper='/home/mei/Pictures/wallpaper/104580093_p0.jpg'

# Special
background='#0b0a0a'
foreground='#d4d9d3'
cursor='#d4d9d3'

# Colors
color0='#0b0a0a'
color1='#5A6A8E'
color2='#807F80'
color3='#6E8D9A'
color4='#8E8E8E'
color5='#9FA09F'
color6='#AFAFAF'
color7='#d4d9d3'
color8='#949793'
color9='#5A6A8E'
color10='#807F80'
color11='#6E8D9A'
color12='#8E8E8E'
color13='#9FA09F'
color14='#AFAFAF'
color15='#d4d9d3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
