# Shell variables
# Generated by 'wal'
wallpaper='/home/mei/Pictures/wallpaper/__shenhe_genshin_impact_drawn_by_mento__b90af792de2d6d6a451a2da1d96137f5.jpg'

# Special
background='#191a1f'
foreground='#e5e7e8'
cursor='#e5e7e8'

# Colors
color0='#191a1f'
color1='#6F7A85'
color2='#788893'
color3='#93959A'
color4='#AFB1B3'
color5='#C3BFB9'
color6='#D0D1D3'
color7='#e5e7e8'
color8='#a0a1a2'
color9='#6F7A85'
color10='#788893'
color11='#93959A'
color12='#AFB1B3'
color13='#C3BFB9'
color14='#D0D1D3'
color15='#e5e7e8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
