# Shell variables
# Generated by 'wal'
wallpaper='/home/mei/Pictures/wallpaper/105821209_p0.png'

# Special
background='#36283d'
foreground='#cedaeb'
cursor='#cedaeb'

# Colors
color0='#36283d'
color1='#71ADE9'
color2='#AB8CAE'
color3='#E59DB1'
color4='#9EA0D3'
color5='#8BB8E9'
color6='#E1B4CE'
color7='#cedaeb'
color8='#9098a4'
color9='#71ADE9'
color10='#AB8CAE'
color11='#E59DB1'
color12='#9EA0D3'
color13='#8BB8E9'
color14='#E1B4CE'
color15='#cedaeb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
