--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mei/Pictures/wallpaper/105821209_p0.png"

-- Special
background="#36283d"
foreground="#cedaeb"
cursor="#cedaeb"

-- Colors
color0="#36283d"
color1="#71ADE9"
color2="#AB8CAE"
color3="#E59DB1"
color4="#9EA0D3"
color5="#8BB8E9"
color6="#E1B4CE"
color7="#cedaeb"
color8="#9098a4"
color9="#71ADE9"
color10="#AB8CAE"
color11="#E59DB1"
color12="#9EA0D3"
color13="#8BB8E9"
color14="#E1B4CE"
color15="#cedaeb"
