--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mei/Pictures/wallpaper/raiden-shogun-yae-miko-genshin-impact-0-hd-wallpaper-1920x1080-uhdpaper.com-645.1_b.jpg"

-- Special
background="#23101c"
foreground="#ebe3e6"
cursor="#ebe3e6"

-- Colors
color0="#23101c"
color1="#C47597"
color2="#B38BA7"
color3="#DDA2AA"
color4="#D2ABC1"
color5="#DFB0CB"
color6="#F0CFD1"
color7="#ebe3e6"
color8="#a49ea1"
color9="#C47597"
color10="#B38BA7"
color11="#DDA2AA"
color12="#D2ABC1"
color13="#DFB0CB"
color14="#F0CFD1"
color15="#ebe3e6"
