# Shell variables
# Generated by 'wal'
wallpaper='/home/rei/Pictures/wallpaper/wallpaper.jpg'

# Special
background='#02131A'
foreground='#bcb4b9'
cursor='#bcb4b9'

# Colors
color0='#02131A'
color1='#653945'
color2='#3C4349'
color3='#4C4C53'
color4='#695861'
color5='#88374A'
color6='#985965'
color7='#bcb4b9'
color8='#837d81'
color9='#653945'
color10='#3C4349'
color11='#4C4C53'
color12='#695861'
color13='#88374A'
color14='#985965'
color15='#bcb4b9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
