--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/rei/Pictures/wallpaper/wallpaper.jpg"

-- Special
background="#02131A"
foreground="#bcb4b9"
cursor="#bcb4b9"

-- Colors
color0="#02131A"
color1="#653945"
color2="#3C4349"
color3="#4C4C53"
color4="#695861"
color5="#88374A"
color6="#985965"
color7="#bcb4b9"
color8="#837d81"
color9="#653945"
color10="#3C4349"
color11="#4C4C53"
color12="#695861"
color13="#88374A"
color14="#985965"
color15="#bcb4b9"
