--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mei/wallpaper/92592349_p0.jpg"

-- Special
background="#08080D"
foreground="#d3dfeb"
cursor="#d3dfeb"

-- Colors
color0="#08080D"
color1="#4E5373"
color2="#975152"
color3="#38578E"
color4="#5D6A95"
color5="#7587B4"
color6="#99A5C5"
color7="#d3dfeb"
color8="#939ca4"
color9="#4E5373"
color10="#975152"
color11="#38578E"
color12="#5D6A95"
color13="#7587B4"
color14="#99A5C5"
color15="#d3dfeb"
