# Shell variables
# Generated by 'wal'
wallpaper='/home/mei/wallpaper/92592349_p0.jpg'

# Special
background='#08080D'
foreground='#d3dfeb'
cursor='#d3dfeb'

# Colors
color0='#08080D'
color1='#4E5373'
color2='#975152'
color3='#38578E'
color4='#5D6A95'
color5='#7587B4'
color6='#99A5C5'
color7='#d3dfeb'
color8='#939ca4'
color9='#4E5373'
color10='#975152'
color11='#38578E'
color12='#5D6A95'
color13='#7587B4'
color14='#99A5C5'
color15='#d3dfeb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
