--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/rei/pictures/wallpaper/OFtuZBWR_4x.jpg"

-- Special
background="#191818"
foreground="#e9e7e4"
cursor="#e9e7e4"

-- Colors
color0="#191818"
color1="#F55152"
color2="#EA6667"
color3="#92807F"
color4="#9F9896"
color5="#C9BCB7"
color6="#D7D5D2"
color7="#e9e7e4"
color8="#a3a19f"
color9="#F55152"
color10="#EA6667"
color11="#92807F"
color12="#9F9896"
color13="#C9BCB7"
color14="#D7D5D2"
color15="#e9e7e4"
