# Shell variables
# Generated by 'wal'
wallpaper='/home/rei/pictures/wallpaper/OFtuZBWR_4x.jpg'

# Special
background='#191818'
foreground='#e9e7e4'
cursor='#e9e7e4'

# Colors
color0='#191818'
color1='#F55152'
color2='#EA6667'
color3='#92807F'
color4='#9F9896'
color5='#C9BCB7'
color6='#D7D5D2'
color7='#e9e7e4'
color8='#a3a19f'
color9='#F55152'
color10='#EA6667'
color11='#92807F'
color12='#9F9896'
color13='#C9BCB7'
color14='#D7D5D2'
color15='#e9e7e4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
