# Shell variables
# Generated by 'wal'
wallpaper='/home/mei/Pictures/Wallpaper/99690898_p0.jpg'

# Special
background='#0F1313'
foreground='#daa5bd'
cursor='#daa5bd'

# Colors
color0='#0F1313'
color1='#2E3350'
color2='#4F344B'
color3='#68524D'
color4='#AE484E'
color5='#975B69'
color6='#7F6C84'
color7='#daa5bd'
color8='#987384'
color9='#2E3350'
color10='#4F344B'
color11='#68524D'
color12='#AE484E'
color13='#975B69'
color14='#7F6C84'
color15='#daa5bd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
