# Shell variables
# Generated by 'wal'
wallpaper='/home/mei/Pictures/wallpaper/95215205_p0.jpg'

# Special
background='#16070f'
foreground='#e9e1e4'
cursor='#e9e1e4'

# Colors
color0='#16070f'
color1='#AC748F'
color2='#AA8C96'
color3='#A593A6'
color4='#E4A2A8'
color5='#9FAACF'
color6='#D9C1C8'
color7='#e9e1e4'
color8='#a39d9f'
color9='#AC748F'
color10='#AA8C96'
color11='#A593A6'
color12='#E4A2A8'
color13='#9FAACF'
color14='#D9C1C8'
color15='#e9e1e4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
