--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mei/Pictures/wallpaper/95215205_p0.jpg"

-- Special
background="#16070f"
foreground="#e9e1e4"
cursor="#e9e1e4"

-- Colors
color0="#16070f"
color1="#AC748F"
color2="#AA8C96"
color3="#A593A6"
color4="#E4A2A8"
color5="#9FAACF"
color6="#D9C1C8"
color7="#e9e1e4"
color8="#a39d9f"
color9="#AC748F"
color10="#AA8C96"
color11="#A593A6"
color12="#E4A2A8"
color13="#9FAACF"
color14="#D9C1C8"
color15="#e9e1e4"
