--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mei/Pictures/Wallpaper/FlFl4LaaEAECNWT.jpeg"

-- Special
background="#030105"
foreground="#c5c4cb"
cursor="#c5c4cb"

-- Colors
color0="#030105"
color1="#767787"
color2="#706391"
color3="#877985"
color4="#8B74CA"
color5="#7E8493"
color6="#878896"
color7="#c5c4cb"
color8="#89898e"
color9="#767787"
color10="#706391"
color11="#877985"
color12="#8B74CA"
color13="#7E8493"
color14="#878896"
color15="#c5c4cb"
