# Shell variables
# Generated by 'wal'
wallpaper='/home/mei/Pictures/Wallpaper/FlFl4LaaEAECNWT.jpeg'

# Special
background='#030105'
foreground='#c5c4cb'
cursor='#c5c4cb'

# Colors
color0='#030105'
color1='#767787'
color2='#706391'
color3='#877985'
color4='#8B74CA'
color5='#7E8493'
color6='#878896'
color7='#c5c4cb'
color8='#89898e'
color9='#767787'
color10='#706391'
color11='#877985'
color12='#8B74CA'
color13='#7E8493'
color14='#878896'
color15='#c5c4cb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
