--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/minako/Pictures/wallpaper/02LtPuZJ_4x.jpg"

-- Special
background="#211818"
foreground="#eee6e7"
cursor="#eee6e7"

-- Colors
color0="#211818"
color1="#CEB0B2"
color2="#D8C1BE"
color3="#D8BEC1"
color4="#E1BEC2"
color5="#DCC5C7"
color6="#E6D2D3"
color7="#eee6e7"
color8="#a6a1a1"
color9="#CEB0B2"
color10="#D8C1BE"
color11="#D8BEC1"
color12="#E1BEC2"
color13="#DCC5C7"
color14="#E6D2D3"
color15="#eee6e7"
