# Shell variables
# Generated by 'wal'
wallpaper='/home/minako/Pictures/wallpaper/02LtPuZJ_4x.jpg'

# Special
background='#211818'
foreground='#eee6e7'
cursor='#eee6e7'

# Colors
color0='#211818'
color1='#CEB0B2'
color2='#D8C1BE'
color3='#D8BEC1'
color4='#E1BEC2'
color5='#DCC5C7'
color6='#E6D2D3'
color7='#eee6e7'
color8='#a6a1a1'
color9='#CEB0B2'
color10='#D8C1BE'
color11='#D8BEC1'
color12='#E1BEC2'
color13='#DCC5C7'
color14='#E6D2D3'
color15='#eee6e7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
