--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mei/Pictures/wallpaper/105478998_p0.jpg"

-- Special
background="#2c2937"
foreground="#ebe3eb"
cursor="#ebe3eb"

-- Colors
color0="#2c2937"
color1="#B0ABCA"
color2="#CCB9CE"
color3="#B7CFE8"
color4="#D3C7D7"
color5="#D1D4E9"
color6="#E5DEE0"
color7="#ebe3eb"
color8="#a49ea4"
color9="#B0ABCA"
color10="#CCB9CE"
color11="#B7CFE8"
color12="#D3C7D7"
color13="#D1D4E9"
color14="#E5DEE0"
color15="#ebe3eb"
