# Shell variables
# Generated by 'wal'
wallpaper='/home/mei/Pictures/wallpaper/105478998_p0.jpg'

# Special
background='#2c2937'
foreground='#ebe3eb'
cursor='#ebe3eb'

# Colors
color0='#2c2937'
color1='#B0ABCA'
color2='#CCB9CE'
color3='#B7CFE8'
color4='#D3C7D7'
color5='#D1D4E9'
color6='#E5DEE0'
color7='#ebe3eb'
color8='#a49ea4'
color9='#B0ABCA'
color10='#CCB9CE'
color11='#B7CFE8'
color12='#D3C7D7'
color13='#D1D4E9'
color14='#E5DEE0'
color15='#ebe3eb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
