# Shell variables
# Generated by 'wal'
wallpaper='/home/mei/Pictures/wallpaper/99735572_p0.png'

# Special
background='#0a0a0d'
foreground='#e5e5e8'
cursor='#e5e5e8'

# Colors
color0='#0a0a0d'
color1='#92696B'
color2='#91837D'
color3='#A29DA0'
color4='#C9B6B2'
color5='#C8C0BE'
color6='#D4D3D7'
color7='#e5e5e8'
color8='#a0a0a2'
color9='#92696B'
color10='#91837D'
color11='#A29DA0'
color12='#C9B6B2'
color13='#C8C0BE'
color14='#D4D3D7'
color15='#e5e5e8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
