# Shell variables
# Generated by 'wal'
wallpaper='/home/mei/Pictures/wallpaper/105681177_p0.jpg'

# Special
background='#101216'
foreground='#d1cfdb'
cursor='#d1cfdb'

# Colors
color0='#101216'
color1='#2D5095'
color2='#3341AE'
color3='#5E6699'
color4='#887B96'
color5='#728CC4'
color6='#9F94A1'
color7='#d1cfdb'
color8='#929099'
color9='#2D5095'
color10='#3341AE'
color11='#5E6699'
color12='#887B96'
color13='#728CC4'
color14='#9F94A1'
color15='#d1cfdb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
