--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mei/Pictures/wallpaper/99767207_p0.jpg"

-- Special
background="#040404"
foreground="#e9e2e2"
cursor="#e9e2e2"

-- Colors
color0="#040404"
color1="#A47B85"
color2="#989191"
color3="#AEADAD"
color4="#CDB6B7"
color5="#D6BCC2"
color6="#D3D2D2"
color7="#e9e2e2"
color8="#a39e9e"
color9="#A47B85"
color10="#989191"
color11="#AEADAD"
color12="#CDB6B7"
color13="#D6BCC2"
color14="#D3D2D2"
color15="#e9e2e2"
