# Shell variables
# Generated by 'wal'
wallpaper='/home/mei/Pictures/wallpaper/99767207_p0.jpg'

# Special
background='#040404'
foreground='#e9e2e2'
cursor='#e9e2e2'

# Colors
color0='#040404'
color1='#A47B85'
color2='#989191'
color3='#AEADAD'
color4='#CDB6B7'
color5='#D6BCC2'
color6='#D3D2D2'
color7='#e9e2e2'
color8='#a39e9e'
color9='#A47B85'
color10='#989191'
color11='#AEADAD'
color12='#CDB6B7'
color13='#D6BCC2'
color14='#D3D2D2'
color15='#e9e2e2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
