--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mei/Pictures/wallpaper/63977166_p0.png"

-- Special
background="#0D091A"
foreground="#e6e0e9"
cursor="#e6e0e9"

-- Colors
color0="#0D091A"
color1="#916EA0"
color2="#AE66B6"
color3="#5A9FD4"
color4="#9C8FB1"
color5="#9EA2D6"
color6="#CABCCA"
color7="#e6e0e9"
color8="#a19ca3"
color9="#916EA0"
color10="#AE66B6"
color11="#5A9FD4"
color12="#9C8FB1"
color13="#9EA2D6"
color14="#CABCCA"
color15="#e6e0e9"
