# Shell variables
# Generated by 'wal'
wallpaper='/home/mei/Pictures/wallpaper/63977166_p0.png'

# Special
background='#0D091A'
foreground='#e6e0e9'
cursor='#e6e0e9'

# Colors
color0='#0D091A'
color1='#916EA0'
color2='#AE66B6'
color3='#5A9FD4'
color4='#9C8FB1'
color5='#9EA2D6'
color6='#CABCCA'
color7='#e6e0e9'
color8='#a19ca3'
color9='#916EA0'
color10='#AE66B6'
color11='#5A9FD4'
color12='#9C8FB1'
color13='#9EA2D6'
color14='#CABCCA'
color15='#e6e0e9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
