# Shell variables
# Generated by 'wal'
wallpaper='/home/mei/Pictures/wallpaper/3jifB5EI_2x.jpg'

# Special
background='#0b0c0c'
foreground='#cccccb'
cursor='#cccccb'

# Colors
color0='#0b0c0c'
color1='#8E544F'
color2='#847A79'
color3='#83817F'
color4='#847F80'
color5='#989797'
color6='#A29F9D'
color7='#cccccb'
color8='#8e8e8e'
color9='#8E544F'
color10='#847A79'
color11='#83817F'
color12='#847F80'
color13='#989797'
color14='#A29F9D'
color15='#cccccb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
