--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mei/Pictures/wallpaper/3jifB5EI_2x.jpg"

-- Special
background="#0b0c0c"
foreground="#cccccb"
cursor="#cccccb"

-- Colors
color0="#0b0c0c"
color1="#8E544F"
color2="#847A79"
color3="#83817F"
color4="#847F80"
color5="#989797"
color6="#A29F9D"
color7="#cccccb"
color8="#8e8e8e"
color9="#8E544F"
color10="#847A79"
color11="#83817F"
color12="#847F80"
color13="#989797"
color14="#A29F9D"
color15="#cccccb"
