--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mei/Pictures/wallpaper/IO5ogxzd_4x.jpg"

-- Special
background="#1a161d"
foreground="#e2e9f5"
cursor="#e2e9f5"

-- Colors
color0="#1a161d"
color1="#B3B2CA"
color2="#C8BACB"
color3="#DCD4DE"
color4="#E9D2CE"
color5="#C5C9E1"
color6="#D1D7F9"
color7="#e2e9f5"
color8="#9ea3ab"
color9="#B3B2CA"
color10="#C8BACB"
color11="#DCD4DE"
color12="#E9D2CE"
color13="#C5C9E1"
color14="#D1D7F9"
color15="#e2e9f5"
