# Shell variables
# Generated by 'wal'
wallpaper='/home/mei/Pictures/Wallpaper/war-devil-devil-hunter-from-chainsaw-man-wallpaper-3840x2160_54.jpg'

# Special
background='#0a090c'
foreground='#c7c2c5'
cursor='#c7c2c5'

# Colors
color0='#0a090c'
color1='#354B50'
color2='#61595F'
color3='#8A1A18'
color4='#8E2426'
color5='#91645C'
color6='#8D7E81'
color7='#c7c2c5'
color8='#8b8789'
color9='#354B50'
color10='#61595F'
color11='#8A1A18'
color12='#8E2426'
color13='#91645C'
color14='#8D7E81'
color15='#c7c2c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
