--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mei/Pictures/Wallpaper/war-devil-devil-hunter-from-chainsaw-man-wallpaper-3840x2160_54.jpg"

-- Special
background="#0a090c"
foreground="#c7c2c5"
cursor="#c7c2c5"

-- Colors
color0="#0a090c"
color1="#354B50"
color2="#61595F"
color3="#8A1A18"
color4="#8E2426"
color5="#91645C"
color6="#8D7E81"
color7="#c7c2c5"
color8="#8b8789"
color9="#354B50"
color10="#61595F"
color11="#8A1A18"
color12="#8E2426"
color13="#91645C"
color14="#8D7E81"
color15="#c7c2c5"
