--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mei/Pictures/wallpaper/99735572_p0.png"

-- Special
background="#0a0a0d"
foreground="#e5e5e8"
cursor="#e5e5e8"

-- Colors
color0="#0a0a0d"
color1="#92696B"
color2="#91837D"
color3="#A29DA0"
color4="#C9B6B2"
color5="#C8C0BE"
color6="#D4D3D7"
color7="#e5e5e8"
color8="#a0a0a2"
color9="#92696B"
color10="#91837D"
color11="#A29DA0"
color12="#C9B6B2"
color13="#C8C0BE"
color14="#D4D3D7"
color15="#e5e5e8"
