--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mei/Pictures/wallpaper/__shenhe_genshin_impact_drawn_by_mento__b90af792de2d6d6a451a2da1d96137f5.jpg"

-- Special
background="#191a1f"
foreground="#e5e7e8"
cursor="#e5e7e8"

-- Colors
color0="#191a1f"
color1="#6F7A85"
color2="#788893"
color3="#93959A"
color4="#AFB1B3"
color5="#C3BFB9"
color6="#D0D1D3"
color7="#e5e7e8"
color8="#a0a1a2"
color9="#6F7A85"
color10="#788893"
color11="#93959A"
color12="#AFB1B3"
color13="#C3BFB9"
color14="#D0D1D3"
color15="#e5e7e8"
